title: Rationalized Hubris
description: Writing things that almost make sense.
author: Luke Silver
baseurl: ""
url: "https://rationalizedhubris.com" 

remote_theme: huangyz0918/moving
plugins:
  - jekyll-remote-theme